In [2]:
import warnings
warnings.filterwarnings('ignore',category=DeprecationWarning)

import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer,TfidfTransformer
from sklearn.metrics.pairwise import cosine_similarity

# **Question No.1**

In [3]:
s1 ="sunshine state enjoy sunshine"
s2="brown fox jump high, brown fox run"
s3="sunshine state fox run fast"

sentences = np.array([s1,s2,s3])
sentences

array(['sunshine state enjoy sunshine',
       'brown fox jump high, brown fox run',
       'sunshine state fox run fast'], dtype='<U34')

In [4]:
vectorizer = CountVectorizer()
bagOfWords = vectorizer.fit_transform(sentences)
print(vectorizer.get_feature_names())

['brown', 'enjoy', 'fast', 'fox', 'high', 'jump', 'run', 'state', 'sunshine']


/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [5]:
print(vectorizer.vocabulary_)

{'sunshine': 8, 'state': 7, 'enjoy': 1, 'brown': 0, 'fox': 3, 'jump': 5, 'high': 4, 'run': 6, 'fast': 2}


In [6]:
print(bagOfWords.toarray())

[[0 1 0 0 0 0 0 1 2]
 [2 0 0 2 1 1 1 0 0]
 [0 0 1 1 0 0 1 1 1]]


In [7]:
bow = pd.DataFrame(bagOfWords.toarray(),index=['s1','s2','s3'],columns = vectorizer.get_feature_names())
bow

brown  enjoy  fast  fox  high  jump  run  state  sunshine
s1      0      1     0    0     0     0    0      1         2
s2      2      0     0    2     1     1    1      0         0
s3      0      0     1    1     0     0    1      1         1

In [8]:
#calculating the term frequency
tf_idf_vectorizer = TfidfVectorizer(use_idf=False)
tf = tf_idf_vectorizer.fit_transform(sentences)
tf

<3x9 sparse matrix of type '<class 'numpy.float64'>'
	with 13 stored elements in Compressed Sparse Row format>

In [9]:
tf_df = pd.DataFrame(tf.toarray(),index=['s1','s2','s3'],columns = vectorizer.get_feature_names())
tf_df

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


brown     enjoy      fast       fox      high      jump       run  \
s1  0.000000  0.408248  0.000000  0.000000  0.000000  0.000000  0.000000   
s2  0.603023  0.000000  0.000000  0.603023  0.301511  0.301511  0.301511   
s3  0.000000  0.000000  0.447214  0.447214  0.000000  0.000000  0.447214   

       state  sunshine  
s1  0.408248  0.816497  
s2  0.000000  0.000000  
s3  0.447214  0.447214

In [10]:
tf_idf_vectorizers = TfidfVectorizer(use_idf=True)
tf_idf = tf_idf_vectorizers.fit_transform(sentences)
idf = pd.DataFrame({'feature':vectorizer.get_feature_names(), 'idf':tf_idf_vectorizers.idf_})
idf

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


feature       idf
0     brown  1.693147
1     enjoy  1.693147
2      fast  1.693147
3       fox  1.287682
4      high  1.693147
5      jump  1.693147
6       run  1.287682
7     state  1.287682
8  sunshine  1.287682

In [11]:
#print tfidf
tf_idf_pd = pd.DataFrame(tf_idf.toarray(),index=['s1','s2','s3'],columns = vectorizer.get_feature_names())
tf_idf_pd

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


brown    enjoy      fast       fox      high      jump       run  \
s1  0.000000  0.50689  0.000000  0.000000  0.000000  0.000000  0.000000   
s2  0.670703  0.00000  0.000000  0.510087  0.335352  0.335352  0.255044   
s3  0.000000  0.00000  0.549351  0.417796  0.000000  0.000000  0.417796   

       state  sunshine  
s1  0.385503  0.771006  
s2  0.000000  0.000000  
s3  0.417796  0.417796

#**Question No.2** 
##Cosine Similarity between s1 and s3

In [12]:
cosArray = tf.toarray()

In [13]:
cosArray

array([[0.        , 0.40824829, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.40824829, 0.81649658],
       [0.60302269, 0.        , 0.        , 0.60302269, 0.30151134,
        0.30151134, 0.30151134, 0.        , 0.        ],
       [0.        , 0.        , 0.4472136 , 0.4472136 , 0.        ,
        0.        , 0.4472136 , 0.4472136 , 0.4472136 ]])

In [14]:
print(cosine_similarity([cosArray[0]], [cosArray[2]]))

[[0.54772256]]
